#!/bin/bash
file1=$1
file2=$2
file3=$3
file4=$4
file5=$5
if [ -z "$file1"  ]; then
	echo "Falta fichero"

else
	 if [ -f "$file1" ];then
	 echo "Existe el fichero $file1"

else
 	echo "No existe el fichero $file1"
fi
fi

if [ -z "$file2"  ]; then
        echo "Falta fichero"

else
         if [ -f "$file2" ];then
         echo "Existe el fichero $file2"

else
        echo "No existe el fichero $file2"
fi
fi

if [ -z "$file3"  ]; then
        echo "Falta fichero"

else
         if [ -f "$file3" ];then
         echo "Existe el fichero $file3"

else
        echo "No existe el fichero $file3"
fi
fi

if [ -z "$file4"  ]; then
        echo "Falta fichero"

else
         if [ -f "$file4" ];then
         echo "Existe el fichero $file4"

else
        echo "No existe el fichero $file4"
fi
fi

if [ -z "$file5"  ]; then
        echo "Falta fichero"

else
         if [ -f "$file5" ];then
         echo "Existe el fichero $file5"

else
        echo "No existe el fichero $file5"
fi
fi

>total.txt

cat $* >total.txt
echo "Fichero total.txt generado"
