#!/bin/bash
file1=$1
file2=$2
file3=$3
file4=$4
if [ -z "$file1" ]; then
  echo "Falta fichero"
	exit 0
fi

if [ -z "$file2" ]; then
   echo "Falta fichero"
	exit 0
fi

if [ -z "$file3" ]; then
   echo "Falta fichero"
	exit 0
fi

if [ -z "$file4" ]; then
   echo "Falta fichero"
	exit 0
fi
>total.txt

cat $* >total.txt






